/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder_3 (
    input [15:0] firstNumber,
    input [15:0] secondNumber,
    input alufn,
    output reg [15:0] answer,
    output reg z
  );
  
  
  
  always @* begin
    answer = 4'bxxxx;
    if (firstNumber == secondNumber) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
    if (alufn == 1'h0) begin
      answer = firstNumber + secondNumber;
    end
    if (alufn == 1'h1) begin
      answer = firstNumber - secondNumber;
    end
  end
endmodule
