/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module bool_4 (
    input [15:0] firstNumber,
    input [15:0] secondNumber,
    input [3:0] alufn,
    output reg [15:0] answer
  );
  
  
  
  always @* begin
    answer = 4'bxxxx;
    if (alufn == 4'h8) begin
      answer[0+15-:16] = firstNumber[0+15-:16] & secondNumber[0+15-:16];
    end
    if (alufn == 4'he) begin
      answer[0+15-:16] = firstNumber[0+15-:16] | secondNumber[0+15-:16];
    end
    if (alufn == 4'h6) begin
      answer[0+15-:16] = firstNumber[0+15-:16] ^ secondNumber[0+15-:16];
    end
    if (alufn == 4'ha) begin
      answer[0+15-:16] = firstNumber[0+15-:16];
    end
  end
endmodule
