/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module nv_11 (
    input [15:0] firstNumber,
    input [15:0] secondNumber,
    input [15:0] sum,
    input a31,
    input b31,
    input s31,
    input [1:0] alufn,
    output reg v,
    output reg n,
    output reg z
  );
  
  
  
  always @* begin
    n = s31;
    if (alufn == 2'h1) begin
      v = ((~b31) & a31 & (~s31)) | (b31 & (~a31) & s31);
    end else begin
      if (alufn == 2'h0) begin
        v = (b31 & a31 & (~s31)) | ((~b31) & (~a31) & s31);
      end else begin
        if (alufn == 2'h2) begin
          if (firstNumber != 1'h0 && sum / firstNumber != secondNumber) begin
            v = 1'h1;
          end else begin
            v = 1'h0;
          end
        end else begin
          v = 1'h0;
        end
      end
    end
    if (sum == 16'h0000) begin
      z = 1'h1;
    end else begin
      z = 1'h0;
    end
  end
endmodule
