/*
   This file was generated automatically by Alchitry Labs version 1.1.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module nv_7 (
    input a31,
    input b31,
    input s31,
    input alufn,
    output reg v,
    output reg n
  );
  
  
  
  always @* begin
    n = s31;
    if (alufn == 1'h1) begin
      v = (-b31 & a31 & (~s31)) | ((~(-b31)) & (~a31) & s31);
    end else begin
      v = (b31 & a31 & (~s31)) | ((~b31) & (~a31) & s31);
    end
  end
endmodule
